# Generated by Django 3.2.4 on 2021-06-13 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
    ]
