# Generated by Django 3.2.4 on 2021-06-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
