# Generated by Django 3.2.4 on 2021-06-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0005_auto_20210613_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='ogr',
            new_name='org',
        ),
    ]
