# Generated by Django 3.2.4 on 2021-07-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0006_rename_ogr_participant_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=1000)),
            ],
        ),
    ]
