# Generated by Django 3.2.4 on 2021-07-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0007_certificate_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='starting_date',
        ),
        migrations.AddField(
            model_name='event',
            name='ending_date',
            field=models.DateField(null=True),
        ),
    ]
